name: flutter_crypto_wallet
description: A modern crypto wallet app built with Flutter 3.27 and Dart 3
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI & Animation
  flutter_animate: ^4.5.0
  lottie: ^3.1.3
  flutter_screenutil: ^5.9.3

  # Navigation & State Management
  go_router: ^16.3.0
  flutter_riverpod: ^3.0.3
  dartz: ^0.10.1

  # Networking & Serialization
  dio: ^5.8.0
  shared_preferences: ^2.3.2
  intl: ^0.20.2

  # Layout & Utils
  responsive_builder: ^0.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  riverpod_generator: ^3.0.1



flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/coins/